# Generated by Django 5.0.6 on 2024-06-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
