# Generated by Django 5.0.6 on 2024-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_publicaciones_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
